### ISSUE TITLE
Change Vagrant Box Provider to support VMware

### ISSUE THREAD

**Issue by armon** [obfuscurity/synthesize#34]
Currently the Vagrant box is defined as:

```
config.vm.box = "synthesize"
config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
```

That provider is Virtualbox only. For people with the Vagrant VMware adaptor, it forces a downgrade.
Instead, if you define it as:

```
config.vm.box = "mayflower/trusty64-puppet3"
```

Then you still get trusty 64bit, but they provide a virtual box and VMware version. Thanks!

**Comment by obfuscurity** [comment]
Any opinion on using something like https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x64 instead of the mayflower box? It's the most popular trusty box that also supports VMware.

https://atlas.hashicorp.com/boxes/search?order=desc&page=1&provider=vmware_desktop&q=trusty&sort=downloads&utf8=%E2%9C%93

**Comment by armon** [comment]
@obfuscurity I have no preference! puphpet boxes are great as well.

**Comment by obfuscurity** [comment]
Sorry it took so long to get around to this.
