### ISSUE TITLE
Bump txamqp version to support recent versions of RabbitMQ

### ISSUE THREAD

**Issue by CMihalcik** [obfuscurity/synthesize#54]
Enabling AMQP against RabbitMQ version [3.2.4 (4 March 2014)](https://www.rabbitmq.com/release-notes/README-3.2.4.txt) or [3.5.4 (22 July 2015)](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_5_4) results in an [error](https://github.com/obfuscurity/synthesize/files/690849/txamqp-error-log.txt) on startup.

Per https://answers.launchpad.net/txamqp/+question/164751 upgrading txamqp resolves the issue.

**Comment by obfuscurity** [comment]
I'm torn on the "best" approach to fixing this. I guess your fix in https://github.com/CMihalcik/synthesize/commit/719050f7edec3e7a40526299140320a5db20d09a makes as much sense as any, especially since it's an optional dep in Carbon. I don't necessarily want to actively support AMQP in Synthesize (since I don't use it personally) but there dependencies are light, so I think it's probably ok.

Would you mind submitting a patch here?

**Comment by obfuscurity** [comment]
Oh duh, never mind. I didn't realize how easy GitHub made it to pull your patch back in as a PR. See #55.

**Comment by obfuscurity** [comment]
Thanks @CMihalcik!
